version: '3.8'

services:
  chen:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    volumes:
     - type: bind
       source: /Users/songchen/Documents/project/HWsoft/Huawei
       target: /app
    working_dir: /app
    stdin_open: true  # 保持标准输入打开
    tty: true         # 启用伪终端